### ISSUE TITLE
Games Directory Permissions Issue?

### ISSUE THREAD

**Issue by mccorkled** [shawly/docker-ps3netsrv#24]
Seems like the wrong user has permissions to the /games directory. I have tried several ways to give user 1028 the permissions. Thank you.

**I have read and followed [all troubleshooting steps from the README.md](https://github.com/shawly/docker-ps3netsrv#troubleshooting)?**

```
SSBoYXZlIHJlYWQsIGZvbGxvd2VkIGFuZCB0cmllZCBldmVyeSB0cm91Ymxlc2hvb3Rpbmcgc3RlcCwgYnV0IGl0IHN0aWxsIGRvZXNuJ3Qgd29yaywgcGxlYXNlIGhlbHAgbWUu
```

**System configuration:**  
Please execute **every** command here and post the output. I will not answer tickets where these outputs are missing.

Output of `docker version`:
```

Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.13
 Git commit:        b455053
 Built:             Thu Aug 19 07:13:24 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.13
  Git commit:       a3bc36f
  Built:            Thu Aug 19 07:11:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        31cc25f16f5eba4d0f53e35374532873744f4b31
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00


```

Output of `docker ps -a -f "ancestor=shawly/ps3netsrv"`:
```
CONTAINER ID   IMAGE                     COMMAND   CREATED      STATUS              PORTS                      NAMES
6b844771f777   shawly/ps3netsrv:latest   "/init"   2 days ago   Up About a minute   0.0.0.0:38008->38008/tcp   Ps3netsrv

```

Output of `docker logs CONTAINERNAME` (replace *CONTAINERNAME* with your ps3netsrv container's name):
```
-------------------------------------
GID/UID
-------------------------------------

User uid:    1028
User gid:    100
-------------------------------------

[cont-init.d] 00-adduser: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-04-12 00:08:45.833069450  ps3netsrv build 20220330 (mod by aldostools)

```

Output of `id` (you should be logged in with the user that owns your games directory):
```
uid=1028(administrator) gid=100(users) groups=100(users),101(administrators)

```

Output of `docker exec --user ps3netsrv CONTAINERNAME id` (replace *CONTAINERNAME* with your ps3netsrv container's name):
```
uid=1028(ps3netsrv) gid=100(users) groups=100(users)

```

Output of `ls -l /path/to/your/games/folder`:
```
drwxrwx---+ 1 root administrators 460 Apr 11 21:25 GAMES
drwxrwx---+ 1 root administrators  56 Apr 11 20:37 PS3ISO

```

Output of `docker exec CONTAINERNAME ls -l /games` (replace *CONTAINERNAME* with your ps3netsrv container's name):
```
drwxrwx--- 1 root ps3netsrv 460 Apr 11 21:25 GAMES
drwxrwx--- 1 root ps3netsrv  56 Apr 11 20:37 PS3ISO

```

My docker run command or my docker-compose.yml:
```
Ps3netsrv:
    container_name: Ps3netsrv
    cpu_shares: 50
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - S6_OVERLAY_RELEASE=https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-amd64.tar.gz
      - USER_ID=1028
      - GROUP_ID=100
      - TZ=America/New_York
    hostname: Ps3netsrv
    image: shawly/ps3netsrv:latest
    ipc: shareable
    labels:
      org.opencontainers.image.created: 2022-04-01T21:20:03Z
      org.opencontainers.image.description: $IMAGE_DESCRIPTION
      org.opencontainers.image.revision: c277470e11de07d489f510f444e6046fe84e5da0
      org.opencontainers.image.source: https://github.com/shawly/docker-ps3netsrv
      org.opencontainers.image.title: $IMAGE_TITLE
      org.opencontainers.image.url: https://github.com/shawly/docker-ps3netsrv
      org.opencontainers.image.vendor: shawly
      org.opencontainers.image.version: $APP_VERSION
    logging:
      driver: db
      options: {}
    mac_address: 02:42:ac:11:00:08
    networks:
      - bridge
    ports:
      - 38008:38008/tcp
    stdin_open: true
    tty: true
    volumes:
      - '/volume1/Hyperspin/Games/Sony Playstation 3/_SNAPS:/games:rw'
networks:
  bridge:
    external: true

```
